-- Prompt 17 E2E cleanup. Run after `npm run test:e2e` (its own
-- companion to e2e-seed.sql). Removes both what the seed script created
-- AND whatever the tests themselves created live (list_submissions from
-- journeys 3/4/IDOR, and the school_lists/versions/items that journey
-- 4's real approve_submission() call publishes) -- see
-- docs/development/e2e-testing.md.
--
-- analytics_events rows generated by the tests (school_view,
-- commerce_click, whatsapp_click, ...) are NEVER deleted -- same
-- established practice as every other prompt's live testing this
-- project has done (event counts are real historical usage data); only
-- the FKs that would otherwise dangle once the test rows below are
-- deleted are nulled first.

with test_profile_ids as (
  select id from auth.users where email like 'e2e-p17-%@example.com'
),
test_submission_ids as (
  select id from public.list_submissions where submitted_by in (select id from test_profile_ids)
),
-- journey 4's real admin approval creates a genuine school_lists row
-- (approve_submission() -> school_list_versions.submission_id) in
-- addition to the one the seed script inserted directly.
approved_list_ids as (
  select school_list_id from public.school_list_versions where submission_id in (select id from test_submission_ids)
),
all_test_list_ids as (
  select id from public.school_lists where slug like 'e2e-p17-lista-%'
  union
  select school_list_id from approved_list_ids
),
test_partner_ids as (
  select id from public.ecommerce_partners where slug = 'e2e-p17-partner'
),
test_store_ids as (
  select id from public.stores where slug = 'e2e-p17-papelaria'
)
select
  (select count(*) from test_profile_ids) as test_profiles,
  (select count(*) from test_submission_ids) as test_submissions,
  (select count(*) from all_test_list_ids) as test_lists,
  (select count(*) from test_partner_ids) as test_partners,
  (select count(*) from test_store_ids) as test_stores;
-- ^ run this SELECT first to sanity-check counts before the deletes
-- below (expected: 3 profiles, >=3 submissions [IDOR + journey3 +
-- journey4], 2 lists [seed + journey4's approval], 1 partner, 1 store).

-- Null dangling FKs before deleting what they'd point to.
update public.analytics_events set profile_id = null
where profile_id in (select id from auth.users where email like 'e2e-p17-%@example.com');
update public.analytics_events set store_id = null
where store_id in (select id from public.stores where slug = 'e2e-p17-papelaria');
update public.analytics_events set list_id = null
where list_id in (
  select id from public.school_lists where slug like 'e2e-p17-lista-%'
  union
  select school_list_id from public.school_list_versions
  where submission_id in (select id from public.list_submissions where submitted_by in (
    select id from auth.users where email like 'e2e-p17-%@example.com'
  ))
);
update public.analytics_events set partner_id = null
where partner_id in (select id from public.ecommerce_partners where slug = 'e2e-p17-partner');

-- Published lists FIRST: school_list_versions.submission_id references
-- list_submissions, so this must be deleted before the submissions
-- themselves or the FK rejects it (confirmed live -- this ordering was
-- wrong on the first attempt). The one the seed script inserted
-- directly, plus whatever journey 4's real admin approval created.
delete from public.school_list_items where school_list_version_id in (
  select id from public.school_list_versions where school_list_id in (
    select id from public.school_lists where slug like 'e2e-p17-lista-%'
    union
    select school_list_id from public.school_list_versions v2
    join public.list_submissions ls on ls.id = v2.submission_id
    where ls.submitted_by in (select id from auth.users where email like 'e2e-p17-%@example.com')
  )
);
delete from public.school_list_versions where school_list_id in (
  select id from public.school_lists where slug like 'e2e-p17-lista-%'
  union
  select v2.school_list_id from public.school_list_versions v2
  join public.list_submissions ls on ls.id = v2.submission_id
  where ls.submitted_by in (select id from auth.users where email like 'e2e-p17-%@example.com')
) or submission_id in (
  select id from public.list_submissions where submitted_by in (
    select id from auth.users where email like 'e2e-p17-%@example.com'
  )
);
delete from public.school_lists where slug like 'e2e-p17-lista-%'
   or id in (
     select v2.school_list_id from public.school_list_versions v2
     join public.list_submissions ls on ls.id = v2.submission_id
     where ls.submitted_by in (select id from auth.users where email like 'e2e-p17-%@example.com')
   );

-- Submissions the tests created live (IDOR draft, journey 3, journey 4).
delete from public.submission_attachments where submission_id in (
  select id from public.list_submissions where submitted_by in (
    select id from auth.users where email like 'e2e-p17-%@example.com'
  )
);
delete from public.submission_items where submission_id in (
  select id from public.list_submissions where submitted_by in (
    select id from auth.users where email like 'e2e-p17-%@example.com'
  )
);
delete from public.list_submissions where submitted_by in (
  select id from auth.users where email like 'e2e-p17-%@example.com'
);

-- Commerce fixtures.
delete from public.list_product_mappings where ecommerce_product_id in (
  select id from public.ecommerce_products where external_url = 'https://example.com/produto/e2e-p17'
);
delete from public.ecommerce_products where external_url = 'https://example.com/produto/e2e-p17';
delete from public.products where name = 'e2e-p17 Caderno brochura 96 folhas';
delete from public.ecommerce_partners where slug = 'e2e-p17-partner';

-- Store fixture.
delete from public.store_contacts where store_id in (select id from public.stores where slug = 'e2e-p17-papelaria');
delete from public.store_services where store_id in (select id from public.stores where slug = 'e2e-p17-papelaria');
delete from public.stores where slug = 'e2e-p17-papelaria';

-- Audit trail from admin actions during journey 4.
delete from public.audit_logs where actor_id in (
  select id from auth.users where email like 'e2e-p17-%@example.com'
);

-- Users last (everything above references them).
delete from public.profiles where id in (select id from auth.users where email like 'e2e-p17-%@example.com');
delete from auth.users where email like 'e2e-p17-%@example.com';

-- Verify: every count below must be 0.
select
  (select count(*) from auth.users where email like 'e2e-p17-%@example.com') as remaining_users,
  (select count(*) from public.profiles where full_name like 'E2E %') as remaining_profiles,
  (select count(*) from public.list_submissions ls join auth.users u on u.id = ls.submitted_by where u.email like 'e2e-p17-%@example.com') as remaining_submissions,
  (select count(*) from public.school_lists where slug like 'e2e-p17-lista-%') as remaining_seed_lists,
  (select count(*) from public.stores where slug = 'e2e-p17-papelaria') as remaining_stores,
  (select count(*) from public.ecommerce_partners where slug = 'e2e-p17-partner') as remaining_partners,
  (select count(*) from public.products where name = 'e2e-p17 Caderno brochura 96 folhas') as remaining_products;
